<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{

    protected $table = 'events';

    public function delete()
    {
        $tagConnects = TagConnect::select('id')->where('connect_id', $this->id)->where('type', TagConnect::EVENTS);

        $tags = Tag::whereIn('id', $tagConnects->get())->get();
        foreach ($tags as $tag) {
            $tag->count_events = $tag->count_events - 1;
            $tag->save();
        }
        $tagConnects->delete();
        return parent::delete(); // TODO: Change the autogenerated stub

    }
}
