<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Photo extends Model
{
    /**
     * @var string
     */
    protected $table = 'photos';

    /**
     * @return bool|null
     */
    public function delete()
    {
        $array = preg_split('/\//', $this->path);
        $path = implode('\/', array($array[3], $array[4]));
        Storage::disk('local')->delete($path);
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function photoConnect()
    {
        return $this->hasOne(PhotoConnect::class, 'id', 'id');
    }

    /**
     * @param $articleId
     * @return mixed
     */
    public static function getAllPhotosForArticle($articleId)
    {
        $photoConnects = PhotoConnect::article($articleId)->toArray();
        return self::whereIn('id', $photoConnects)->get();
    }

}
